Repository WeTransfer/format_parser, pull requests merged in 2018-04, with the labels that each got.

#83 Add parse_atom_children_and_data_fields support
  README.md
  lib/parsers/moov_parser.rb
  lib/parsers/moov_parser/decoder.rb
  lib/parsers/zip_parser/file_reader.rb
  spec/fixtures/MOOV/M4A/fixture.m4a
  spec/parsers/moov_parser_spec.rb
Labels: bugfix

#97 Double the cache page size once more
  lib/care.rb
Labels: bugfix, security

#98 Fix EXIF parsing in JPEG files
  README.md
  lib/parsers/exif_parser.rb
  lib/parsers/jpeg_parser.rb
  lib/parsers/tiff_parser.rb
  lib/parsers/zip_parser.rb
  lib/parsers/zip_parser/file_reader.rb
  spec/esoteric_formats_spec.rb
  spec/fixtures/JPEG/keynote_recognized_as_jpeg.key
  spec/parsers/exif_parser_spec.rb
  spec/parsers/jpeg_parser_spec.rb
  spec/parsers/zip_parser_spec.rb
Labels: bugfix, formats, perf

#101 Add changelog
  CHANGELOG.md
  CONTRIBUTING.md
Labels: enhancement

#96 Add BMP parser
  lib/parsers/bmp_parser.rb
  spec/fixtures/BMP/test.bmp
  spec/fixtures/BMP/test2.bmp
  spec/parsers/bmp_parser_spec.rb
Labels: formats

#107 Add a binary called `format_parser_inspect`
  exe/format_parser_inspect
  lib/format_parser.rb
  spec/format_parser_inspect_spec.rb
  spec/format_parser_spec.rb
Labels: apidesign, enhancement
